---
- name: We make us some Webservers
  hosts: web,win1
  tasks:
    - import_role: name=myapp
      vars:
        config: "{{ app_config }}"

- name: Ensure HA Proxy
  hosts: ctrl
  tasks:
    - import_role: name=geerlingguy.haproxy
      vars:
        haproxy_frontend_name: 'hafrontend'
        haproxy_frontend_bind_address: '*'
        haproxy_frontend_port: 80
        haproxy_frontend_mode: 'http'

        haproxy_backend_name: 'habackend'
        haproxy_backend_mode: 'http'
        haproxy_backend_balance_method: 'roundrobin'
        haproxy_backend_httpchk: 'HEAD / HTTP/1.1\r\nHost:localhost'

        haproxy_backend_servers:
          - name: debian1
            address: 10.0.1.21
          - name: debian2
            address: 10.0.1.22
          - name: win1
            address: 10.0.1.41


