---

- name: We make us some Webservers
  hosts: web
  become: yes
  tasks:
    - name: nginx package is present
      apt:
        name: nginx
        state: latest
      notify: restart ngnix
    
    - name: deploy our awesome app - index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
    
    - name: deploy our awesome app - image.jpg
      copy:
        src: image.jpg
        dest: /var/www/html/image.jpg
    
  handlers:
    - name: restart ngnix
      service:
        name: nginx.service
        state: restarted
    
