
- name: "Presetup for Test"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Ensure SSH Key is in ~/.ssh/workshop.key"
      copy:
        src: "ssh/workshop.key"
        dest: "~/.ssh/workshop.key"
    - name: "Ensure File Permission"
      file:
        path: "~/.ssh/workshop.key"
        mode: 0600

- name: "Test Windows Hosts"
  hosts: windows
  gather_facts: false
  tasks:
    - win_ping:

- name: "Test Linux Hosts"
  hosts: linux
  gather_facts: false
  tasks:
    - ping: