- name: "Ensure workshop aws vpc {{ workshop.aws.vpc.base_name }}"
  ec2_vpc_net:
    name: "{{ workshop.aws.vpc.base_name }}-attendantid-{{ item }}"
    region: "{{ workshop.aws.region }}"
    cidr_block: "{{ workshop.aws.vpc.cidr }}"
    tags:
      workshop: "{{ workshop.name }}"
      workshop_attendant_id: "{{ item }}"
    state: present
  with_sequence: start=1 end="{{ workshop.attendant_count }}"
  when: "not destroy"

- name: "Ensure workshop aws vpc {{ workshop.aws.vpc.base_name }} is removed"
  ec2_vpc_net:
    name: "{{ workshop.aws.vpc.base_name }}-attendantid-{{ item }}"
    region: "{{ workshop.aws.region }}"
    cidr_block: "{{ workshop.aws.vpc.cidr }}"
    state: absent
  with_sequence: start=1 end="{{ workshop.attendant_count }}"
  when: "destroy"