- name: "Get all EC2 Instance Information for Attendant Instance Configuration Documents"
  ec2_instance_facts:
    region: "{{ workshop.aws.region }}"
    filters:
      "tag:workshop": "{{ workshop.name }}"
      "tag:workshop_attendant_id": "{{ attendant_id }}"
      "instance-state-name": "running"
  register: ec2_instance_result

- name: "Generate Attendant Instance Configuration"
  template:
    src: "assets/attendant.md.j2"
    dest: "output/{{ workshop.name }}-{{ attendant_id }}-aws.md"
